name: Deploy NCP Cloud Function

on:
  push:
    paths:
      - "src/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Zip function code
        run: |
          cd src
          zip -r ../function.zip .

      - name: Deploy with Serverless
        env:
          NCP_ACCESS_KEY: ${{ secrets.NCLOUD_ACCESS_KEY }}
          NCP_SECRET_KEY: ${{ secrets.NCLOUD_SECRET_KEY }}
        run: sls deploy --verbose
